### ISSUE TITLE
Consider creating a separate settings file for tests

### ISSUE THREAD

**Issue by kelseyq** [pydanny/cookiecutter-djangopackage#110]
I saw this in wagtail:
https://github.com/torchbox/wagtail/blob/master/runtests.py#L12
https://github.com/torchbox/wagtail/blob/master/wagtail/tests/settings.py

I'm currently packaging a complex-ish app that needs a decent amount of additions to settings to even run and it seems like a nice idea to package those settings with the tests--thoughts?

**Comment by leportella** [comment]
@pydanny @audreyr can I handle this?

**Comment by pydanny** [comment]
@leportella, certainly you can work on this issue. 😄 

I should also introduce you to @kelseyq. She was at PyCon, but had to work during most of the sprints. She has **core contributor rights**, so may be the one merging your pull request. 

Finally, I loved your [PyCon 2016](https://medium.com/@leportella/a-tale-of-kingdom-far-far-away-in-another-dimension-ccb132b46a74#.jsemjkcps) blog post. I'm honored by the mention. 🎉

**Comment by leportella** [comment]
@pydanny I am honored to have all your help and support, thank you.

@kelseyq I am so sorry I didn't get the chance to meet you, but we can meet next year, hopefully! 

I'll get this issue done as soon as I can (and/or get help as soon as I can)

**Comment by kelseyq** [comment]
👋🏻  @leportella ! I just did this in a package I'm working on, so feel free to ping me if you run into any issues. You'll need to run tests or otherwise run the generated project (not just cookiecutter-djangopackage) to verify that it works--`settings.configure` adds SECRET_KEY and possibly other settings for you that need to be explicitly declared in the separate file.

Ideally I'd like to see a cookiecutter-djangopackage test that does that verification automatically, but we can tackle that in or after the pull request--may turn out to be a bit tricky.

**Comment by leportella** [comment]
Ok, I looked the files today and let me check if I got it right:

I should create a tests/settings.py with similar configuration from example/example/settings.py. There, I should also add the tests I have on INSTALED_APPS.

Did I get it right, @kelseyq?

**Comment by kelseyq** [comment]
"I should create a tests/settings.py with similar configuration from example/example/settings.py"--yup
The second part I don't quite follow. What I meant was that we need to verify in some way that the new settings file works. You can do this manually by generating a project with your changed version of cookiecutter-djangopackage, then going into that project and running tests.py. I would like to see that manual process of verification automated, but we can work on that separately since it doesn't happen right now anyway.

**Comment by kelseyq** [comment]
@leportella eep I hope my incoherent explanation didn't scare you away! Let me know if you're stuck or if I can help at all.

**Comment by leportella** [comment]
@kelseyq I just have a big turn-around in my life! I am moving from work and don't have time just now! As soon as I can I get back at you! Thank you!

**Comment by kelseyq** [comment]
@leportella no worries, and congrats on the transition! we will be happy to have you back whenever!

**Comment by browniebroke** [comment]
> `settings.configure` adds `SECRET_KEY` and possibly other settings for you that need to be explicitly declared in the separate file.

I just attempted to do this change in a project and I confirm that I only had to explicitly declare `SECRET_KEY` for it to work.

I don't mind taking over this ticket if no one is working on this anymore?

**Comment by pydanny** [comment]
Go ahead @browniebroke!

**Comment by browniebroke** [comment]
Gave it a shot in #164. I now realised I've extended a bit the scope of the PR and it's doing quite a few more things. Let me know if you have anything against one of them.

**Comment by browniebroke** [comment]
Django docs about that: https://docs.djangoproject.com/en/1.10/topics/testing/advanced/#using-the-django-test-runner-to-test-reusable-applications
