### ISSUE TITLE
Remove Python 3.2

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-djangopackage#111]
Django hasn't supported Python 3.2 in a while, not supported version works with it anymore.

**Comment by kelseyq** [comment]
I was going by this FAQ entry, which says 3.2 is supported til end of 2016...I don't have a big problem with removing it a few months early though.
https://docs.djangoproject.com/en/1.9/faq/install/#what-python-version-can-i-use-with-django

**Comment by pydanny** [comment]
@kelseyq Wow, didn't know 1.8 was so behind the times. Okay then, I stand corrected. Let's keep it in for now.
