### ISSUE TITLE
Add Django 1.11 to the generated project build matrix

### ISSUE THREAD

**Issue by browniebroke** [pydanny/cookiecutter-djangopackage#193]
### Description

Django 1.11 was [released April 4th](https://docs.djangoproject.com/en/1.11/releases/1.11/), it would be good to add it to the build matrix!

### To note

- This is the first version to support Python 3.6, so ideally we would test with Python 3.6 only Django 1.11.
- Django master branch dropped support for Python 2.7, so we should not run tests with that combination.
- From my experience a few months ago, Travis doesn't play well when specifying `python: 3.5` and running tox environment for 3.6 (or the other way round), it crashed with Interpreter not found, but they've updated their image [recently](https://blog.travis-ci.com/2017-05-04-precise-image-updates), that might have solved that.

### Suggested solution 

A solution that is used by [DRF](https://github.com/encode/django-rest-framework/blob/master/.travis.yml) is to use `travis-tox`. However, it's adding another dependency and the build matrix is quite complex, with a few moving parts.

I'm happy to put together a PR if that sounds reasonable.

**Comment by george-silva** [comment]
this can be closed.

**Comment by browniebroke** [comment]
I think it will be closable once #280 is merged. As far as I can see, Django 1.11 hasn't been added yet.

**Comment by therefromhere** [comment]
#280 has been merged, this can be closed now.
