### ISSUE TITLE
Question:  MakeMigrations in Example App?

### ISSUE THREAD

**Issue by Jaredn** [pydanny/cookiecutter-djangopackage#228]
* 2017-09-18
* Python version: 3.6
* Operating System: Windows (Ubuntu/Bash on Windows technically)

### Description

I was trying to use the example app to makemigrations (and migrate) for my re-usable app.

### What I Did

i ran `python3 manage.py makemigrations` from within the example app directory.  It doesn't detect my migrations.

user@hostname:/mnt/c/Users/jared/code/dj-n3-templateplugins/example$ python3 manage.py makemigrations
No changes detected

user@hostname:/mnt/c/Users/jared/code/dj-n3-templateplugins/example$ python3 manage.py showmigrations
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
sessions
 [X] 0001_initial

Notice that makemigrations doesn't detect changes (but there are in my reusable app models.py) and the app doesn't even show up in showmigrations.

### My question:
I'm a noob to this, and simply wondering how I'm supposed to use the 'example' app.  I have a model in my main 'reusable' app, that I'm expecting the example app reads from, but I'm not sure?  Am I supposed to copy code from the main app into the example app in order to test migrations?  I guess I'm just confused at the overall process for how the example app is supposed to be used in a workflow.  I want to test my re-usable app without needing to use an existing one of my projects.

**Comment by pydanny** [comment]
Is your example app listed in INSTALLED_APPS within your settings config?

If not, you will have to provide access to your code base for us to diagnose your problem.

**Comment by Jaredn** [comment]
Yes it is.  code-base is here: https://github.com/Jaredn/dj_n3_templateplugins

**Comment by Jaredn** [comment]
Yes it is.  Codebase (and settings file) is here:
https://github.com/Jaredn/dj_n3_templateplugins/blob/master/example/example/settings.py

**Comment by Jaredn** [comment]
Am I correct in assuming that I need to copy my 'resuable' app code into the 'example' subdirectory?  I don't see anything in the example app that would imply that it could read its parent directory to the 'real' models.py.    That just seemed clunky to me but that seems to be the only way I can see it working.

**Comment by didoarellano** [comment]
@Jaredn Looks like you've resolved your issue. What did you do?

I had to create the `migrations` directory [1] to make migrations work.

In the project root:
```shell
mkdir app_name/migrations
touch app_name/migrations/__init__.py
python manage.py makemigrations
```

The app's migrations showed up in the example app after that.

[1]: Should this directory be part of the cookiecutter-djangopackage scaffolding?
