### ISSUE TITLE
Problem generating new package

### ISSUE THREAD

**Issue by auvipy** [pydanny/cookiecutter-djangopackage#382]
ERROR:pre_gen_project:Invalid Django version "2.0.4". 
ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)

I tried django 1.11. 2.0, 2.0.4 but in every case it failed! what could be the reason?

**Comment by auvipy** [comment]
ubuntu 16.04, python 3.5, interactive options to kickstart a new package skeleton

**Comment by pydanny** [comment]
Which options did you choose? We can't begin to debug your problem without knowing this kind of detail.

**Comment by auvipy** [comment]
almost all, just followed the official docs instructions

**Comment by pydanny** [comment]
Please try again.

**Comment by pydanny** [comment]
Marking this as closed as I believe the problem is resolved. Please reopen if it is still a problem.
