### ISSUE TITLE
List of Django versions is outdated

### ISSUE THREAD

**Issue by joshua-s** [pydanny/cookiecutter-djangopackage#388]
* Date you used Cookiecutter DjangoPackage: 04/12/2018
* Cookiecutter version used, if known: latest
* Python version: 
* Operating System: macOS High Sierra

### Description

I tried to enter the two currently supported versions of Django (1.11, 2.0) as `django_versions`.

This failed with:
```
ERROR:pre_gen_project:Invalid Django version "1.11". 
ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

The reason for the failure is that https://github.com/pydanny/cookiecutter-djangopackage/blob/master/hooks/pre_gen_project.py#L17 does not include the latest versions of Django.

**Comment by pydanny** [comment]
Fixed in 021f0a62864babee91cf887289dde74eb86730d7
