### ISSUE TITLE
Repository URL in README

### ISSUE THREAD

**Issue by uranusjr** [pydanny/cookiecutter-djangopackage#40]
Currently the README uses this when running cookiecutter

    $ cookiecutter https://github.com/pydanny/cookiecutter-dj-package.git

which should probably be

    $ cookiecutter https://github.com/pydanny/cookiecutter-djangopackage.git

to reflect the current repository location instead, although the old one still works now (GitHub seems to maintain a redirection automatically).

**Comment by pydanny** [comment]
Fixed in 13dd6ea92df598412e515da9936638c48944ebe5
