### ISSUE TITLE
'Testall' target doesn't exist.

### ISSUE THREAD

**Issue by Math-ias** [pydanny/cookiecutter-djangopackage#42]
If one runs:
`make help` and gets the help page, they would see: `testall - run tests on every Python version with tox`.

Using this target, one would recieve the error:
```
make: *** No rule to make target `testall'.  Stop.
```

The makefile help should be changed to match the correct target of `test-all`.

I created a pull request for this #41.

**Comment by Math-ias** [comment]
The original cookiecutter package had a pull request similar to this, perhaps this commit should be cherry picked?

https://github.com/audreyr/cookiecutter/pull/297

**Comment by pydanny** [comment]
Thanks for the PR @Math-ias, sorry for my slow response. :stuck_out_tongue_closed_eyes:
