### ISSUE TITLE
Although Python 3.5 is declared in .travis.yml by default it's not available in TravisCI

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-djangopackage#444]
## .travis.yml excerpt

```yaml
env: 
  - TOX_ENV=py36-django-111
  - TOX_ENV=py35-django-111
  - TOX_ENV=py34-django-111
  - TOX_ENV=py27-django-111
```

## Proposal

Introduce `"python_versions": "2.7,3.4,3.6"` `cookiecutter.json` comma-separated list option, and, provided 3.5 is still specified give a WARNING of TravisCI incompatibility at the end of bootstrapping phase.

## TravisCI logs

```bash
$ tox -e $TOX_ENV
# ...
ERROR: InterpreterNotFound: python3.5
___________________________________ summary ____________________________________
ERROR:   py35-django-111: InterpreterNotFound: python3.5
The command "tox -e $TOX_ENV" exited with 1.
```

**Comment by jonathan-s** [comment]
I don't think this an issue any longer so I'm closing this. As far as I know travis supports python 3.5
