### ISSUE TITLE
Add codecov 

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-djangopackage#45]
Providing easy hooks for codecov would be really nice for ensuring quality of projects.

**Comment by stevepeak** [comment]
What kind of hooks are you looking for? We do have 3 different Github statuses and pull request comments ready to use.

**Comment by pydanny** [comment]
Done in 16a7004067e3d0614b13ddbb2d324606e4432ad2.

**Comment by pydanny** [comment]
@stevepeak, how do you mean?

**Comment by stevepeak** [comment]
I may have misread the original question. Thank you :)
