### ISSUE TITLE
Update example usage in readme

### ISSUE THREAD

**Issue by hackebrot** [pydanny/cookiecutter-djangopackage#58]
The [README](https://github.com/pydanny/cookiecutter-djangopackage/blob/master/README.rst) still shows _old-style_ cookiecutter prompts.

This might be confusing to some users.

**Comment by purplediane** [comment]
I will work on this.

**Comment by hackebrot** [comment]
Hey @purplediane! 👋 

Can I help you with this? Please let me know if you have questions.

**Comment by purplediane** [comment]
OMG. I forgot I wrote that! I'm so sorry, I won't be able to look at it until probably February at the earliest. If you want to work on it that would be awesome!

**Comment by williln** [comment]
@hackebrot Do you just mean what the questions are that cookiecutter asks to set up your project, what comes below this section:

>Let's pretend you want to create a reusable Django app called "Blogging-for-Humans

?

**Comment by hackebrot** [comment]
Hey @williln 👋 

I meant the style of the cookiecutter prompts, but it appears that @pydanny fixed this at the PyCon sprints, see b982e9eea50791136517882ad654e998dfb786fa 😝 

I'm closing this issue now. Thanks everyone.
