### ISSUE TITLE
setup.py shouldn't import package

### ISSUE THREAD

**Issue by spookylukey** [pydanny/cookiecutter-djangopackage#65]
The setup.py file does an import on the package itself, in order to get the version.

This becomes an issue if doing "import mypackage" ends up importing other things, especially dependencies (e.g. `mypackage/__init__.py` imports `mydependency` directly or indirectly). The end result can be that setup.py cannot run unless dependencies are already installed.

This means that often a package become uninstallable (with something like pip, which runs setup.py to get a list of dependencies), unless dependencies are installed previously.

The problem is often not apparent to the package maintainer as well, because they rarely install the package from scratch.

If this is fixed, bumpversion config will also need to be fixed.

**Comment by grantmcconnaughey** [comment]
Totally agree. Django-avatar has an implementation of this. https://github.com/grantmcconnaughey/django-avatar/blob/master/setup.py

**Comment by pydanny** [comment]
I'm a huge :+1: for this upgrade. My problem is that I don't have time to do any open source right now besides reviewing simple, clean, very atomic pull requests.

**Comment by grantmcconnaughey** [comment]
I got your PR, Danny. :smile:

**Comment by carltongibson** [comment]
> My problem is that I don't have time to do any open source right now besides reviewing simple, clean, very atomic pull requests. If one can be submitted for this issue, I'll make the time to review it.

I'm gonna get a t-shirt that say this. :-)
