### ISSUE TITLE
The `open` order in make docs is not cross-platform

### ISSUE THREAD

**Issue by JoseTomasTocino** [pydanny/cookiecutter-djangopackage#73]
The `docs` target in the generated `makefile` contains a last order:

	open docs/_build/html/index.html

that fails in Linux systems as `open` is generally a symbolic link to `openvt`, a utility for starting programs in virtual terminals. 

The most similar thing in Linux that I know of would be `xdg-open`, althought there may be better alternatives, but certainly not `open`.

**Comment by audreyr** [comment]
Here's the fix:
https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L2-L12
https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L69

@JoseTomasTocino want to submit a pull request and verify on your side that it works?

**Comment by JoseTomasTocino** [comment]
I've checked the fix and works well on my Linux box! Here's the PR.
