### ISSUE TITLE
Example django site folder

### ISSUE THREAD

**Issue by jangeador** [pydanny/cookiecutter-djangopackage#75]
This template is awesome, however, every time that I use it, I find myself creating an example folder with a django installation inside so that I can develop and test. Would there be any interest in having an example django installation inside a folder which could allow for the app to be debugged right off the install?

**Comment by pydanny** [comment]
Hi @jangeador, I'm still playing catch up after some life issues, so I apologize for responding slowly.

In any case, this is an awesome idea. Yes, there is a lot of interest on my part. If you are still interested, please submit a pull request.

**Comment by jangeador** [comment]
I'm working on it @pydanny although I'm a faithful end user of cookiecutter I am not very familiar with their templating system and it takes me forever to test my work. Any pointers?
