### ISSUE TITLE
Help deploy SPA Flutter web with https production

### ISSUE THREAD

**Issue by elcolie** [pydanny/cookiecutter-djangopackage#975]
* Date you used Cookiecutter DjangoPackage: 22 Jan 2022
* Python version: 3.8.3
* Operating System: OSX 12.1

### Description
>Describe what you were trying to get done.
I am trying to deploy Flutter web app which consumes Django REST API

Tell us what happened, what went wrong, and what you expected to happen.
I can't get `https` and correct route to Flutter and Django

### What I Did
https://community.traefik.io/t/deploy-django-rest-flutter/13166

**Comment by pydanny** [comment]
Completely and totally unrelated to this package.
